// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idcxvdfdaorebutnkorm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkY3h2ZGZkYW9yZWJ1dG5rb3JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0ODQ4MTYsImV4cCI6MjA3NTA2MDgxNn0.12sW78uhy_a_xoaRNgjM5miJ91DgXcrS2eY-GP214QM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});